#!/bin/bash

python3 wav_to_spectrogram.py audio_library audio_library_spectrograms 21
python3 wav_to_spectrogram.py audio_library audio_library_spectrograms 22
python3 wav_to_spectrogram.py audio_library audio_library_spectrograms 23
python3 wav_to_spectrogram.py audio_library audio_library_spectrograms 24
python3 wav_to_spectrogram.py audio_library audio_library_spectrograms 25
python3 wav_to_spectrogram.py audio_library audio_library_spectrograms 26
python3 wav_to_spectrogram.py audio_library audio_library_spectrograms 27
python3 wav_to_spectrogram.py audio_library audio_library_spectrograms 28
python3 wav_to_spectrogram.py audio_library audio_library_spectrograms 29
python3 wav_to_spectrogram.py audio_library audio_library_spectrograms 30
python3 wav_to_spectrogram.py audio_library audio_library_spectrograms 31
