#!/bin/bash

python3 create_library.py 0
python3 create_library.py 1
python3 create_library.py 2
python3 create_library.py 3
python3 create_library.py 4
python3 create_library.py 5
python3 create_library.py 6
python3 create_library.py 7
python3 create_library.py 8
python3 create_library.py 9
python3 create_library.py 10
python3 create_library.py 11
python3 create_library.py 12
python3 create_library.py 13
python3 create_library.py 14
python3 create_library.py 15
python3 create_library.py 16
python3 create_library.py 17
python3 create_library.py 18
python3 create_library.py 19
python3 create_library.py 20
python3 create_library.py 21
python3 create_library.py 22
python3 create_library.py 23
python3 create_library.py 24
python3 create_library.py 25
python3 create_library.py 26
python3 create_library.py 27
python3 create_library.py 28
python3 create_library.py 29
python3 create_library.py 30
python3 create_library.py 31
