python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_390-420.wav.jpg  > compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_420-450.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_450-480.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_480-510.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_510-540.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_540-570.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_570-600.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_600-630.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_60-90.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_630-660.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_660-690.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_690-720.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_720-750.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_750-780.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_780-810.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_810-840.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_840-870.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_870-900.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_900-930.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_90-120.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_930-960.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_960-990.wav.jpg  >> compare_results_3.txt
python3 -u compare_spectrograms.py audio_target_spectrograms/greetings_990-1020.wav.jpg  >> compare_results_3.txt

